INSERT INTO hackathon(hackathon_name, place, hackathon_date) VALUES ('hackathon 1', 'Argentina', '1999-01-08 12:00:00');
INSERT INTO hackathon(hackathon_name, place, hackathon_date) VALUES ('hackathon 2', 'New Zealand', '2000-05-08 12:00:00');
INSERT INTO hackathon(hackathon_name, place, hackathon_date) VALUES ('hackathon 3', 'Germany', '1998-02-15 12:00:00');
INSERT INTO hackathon(hackathon_name, place, hackathon_date) VALUES ('hackathon 4', 'Finland', '2005-08-02 12:00:00');
INSERT INTO hackathon(hackathon_name, place, hackathon_date) VALUES ('hackathon 5', 'Germany', '2009-01-08 12:00:00');

INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('goldenbear311', 'Jana', 'Beutler', 'Germany', 'https://randomuser.me/api/portraits/women/40.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('happyelephant115', 'Lea', 'Petersen', 'Denmark', 'https://randomuser.me/api/portraits/women/92.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('bigbird219 ', 'Asta', 'Rasmussen', 'Denmark', 'https://randomuser.me/api/portraits/women/59.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('greenbear451', 'Cherina', 'Elling', 'Netherlands', 'https://randomuser.me/api/portraits/women/33.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('brownfish994', 'Iida', 'Hokkanen', 'Finland', 'https://randomuser.me/api/portraits/women/23.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('blackpanda924', 'Hedwig', 'Kirstein', 'Germany', 'https://randomuser.me/api/portraits/women/51.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('heavymouse545', 'Vivienne', 'Girard', 'Switzerland', 'https://randomuser.me/api/portraits/women/24.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('yellowfrog479', 'Albert', 'Christensen', 'Denmark', 'https://randomuser.me/api/portraits/men/29.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('goldenbear311', 'Samuel', 'Kemppainen', 'Finland', 'https://randomuser.me/api/portraits/men/19.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('beautifulcat806', 'Delia', 'Brunet', 'Switzerland', 'https://randomuser.me/api/portraits/women/72.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('blacktiger704', 'Charlotte', 'Fournier', 'France', 'https://randomuser.me/api/portraits/women/37.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('tinybear711', 'James', 'Olson', 'Australia', 'https://randomuser.me/api/portraits/men/20.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('brownfrog795', 'Marie', 'Fabre', 'France', 'https://randomuser.me/api/portraits/women/19.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('organicswan279', 'Alice', 'Dupuis', 'France', 'https://randomuser.me/api/portraits/women/77.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('smallmouse598', 'Luca', 'Myran', 'Norway', 'https://randomuser.me/api/portraits/men/30.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('tinygorilla645', 'Loan', 'Robin', 'France', 'https://randomuser.me/api/portraits/men/17.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('yellowbear135', 'Alba', 'Parra', 'Spain', 'https://randomuser.me/api/portraits/women/68.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('happyfrog880', 'Mahé', 'Chevalier', 'France', 'https://randomuser.me/api/portraits/men/82.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('greenmouse232', 'Karine', 'Dumas', 'Switzerland', 'https://randomuser.me/api/portraits/women/86.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('silverlion826', 'Lewis', 'Black', 'United Kingdom', 'https://randomuser.me/api/portraits/men/12.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('greengorilla522', 'Florin', 'Rodriguez', 'Switzerland', 'https://randomuser.me/api/portraits/men/64.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('purplewolf215', 'Emilio', 'Samuelsen', 'Norway', 'https://randomuser.me/api/portraits/men/87.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('lazyostrich641', 'Kristiane', 'Rösler', 'Germany', 'https://randomuser.me/api/portraits/women/67.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('whitelion823', 'Sofia', 'Aalto', 'Finland', 'https://randomuser.me/api/portraits/women/8.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('purplepeacock474', 'Rafael', 'Ramos', 'Spain', 'https://randomuser.me/api/portraits/men/61.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('sadleopard127', 'Jose', 'Chapman', 'Ireland', 'https://randomuser.me/api/portraits/men/55.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('greenmeercat254', 'Benedicte', 'Lehn', 'Norway', 'https://randomuser.me/api/portraits/women/27.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('goldenmouse366', 'Clara', 'Guerrero', 'Spain', 'https://randomuser.me/api/portraits/women/48.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('purplefrog852', 'Manuela', 'Alonso', 'Spain', 'https://randomuser.me/api/portraits/women/78.jpg');
INSERT INTO user_account(username, first_name, last_name, country, profile_picture) VALUES ('crazyfish717', 'Minttu', 'Maijala', 'Finland', 'https://randomuser.me/api/portraits/men/82.jpg');


INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 1, 1);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 2, 2);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 3, 3);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 4, 4);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 5, 5);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 6, 6);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 7, 7);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 8, 8);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 9, 9);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (1, 10, 10);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 1, 11);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 2, 12);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 3, 13);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 4, 14);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 5, 15);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 6, 16);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 7, 17);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 8, 18);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 9, 19);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (2, 10, 20);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 1, 21);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 2, 22);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 3, 23);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 4, 24);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 5, 25);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 6, 26);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 7, 27);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 8, 28);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 9, 29);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (3, 10, 30);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 1, 1);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 2, 2);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 3, 3);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 4, 4);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 5, 5);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 6, 6);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 7, 7);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 8, 8);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 9, 9);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (4, 10, 10);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 1, 11);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 2, 12);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 3, 13);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 4, 14);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 5, 15);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 6, 16);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 7, 17);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 8, 18);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 9, 19);
INSERT INTO hackathon_ranking(hackathon_id, user_account_id, ranking) VALUES (5, 10, 20);

